### ISSUE TITLE
Register the Domain Name in Godaddy

### ISSUE THREAD

**Issue by ServingKhalsa** [ServingKhalsa/servingkhalsa.github.io#1]

**Comment by happybhalla** [comment]
Best DNS plan is available as below:-

godaddy 
khalsaserving.com is available ₹ 199.00 
for the first year with a 2 year registration


Hostgator
khalsaserving.com
is available
Rs. 819 /YR

**Comment by happybhalla** [comment]
We subscribed DNS **http://khalsaserving.com/** for 2 years 2020-06-29 to 2020-06-28

**Comment by happybhalla** [comment]
We are closing this issue as we complete this task by purchased DNS.
